# Generated by Django 4.0.6 on 2022-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='breast_size',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='growth',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='weight',
        ),
        migrations.AddField(
            model_name='post',
            name='breast_size',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='growth',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.IntegerField(default=None),
        ),
    ]
